Repository sanders41/meilisearch-fastapi, pull requests merged in 2022-03, with the labels that each got.

#222 Bump mypy pre-commit hook from 0.931 to 0.940
  .pre-commit-config.yaml
Labels: dependencies, skip-changelog

#215 Update for Meilisearch v0.26.0
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  meilisearch_fastapi/models/tenant_token.py
  meilisearch_fastapi/routes/meilisearch_routes.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_meilisearch_routes.py
Labels: enhancement

#223 Bump version
  pyproject.toml
Labels: skip-changelog

#227 fixed issue-225 removed @pytest.mark.asyncio fixture from testcases
  tests/conftest.py
  tests/test_document_routes.py
  tests/test_index_routes.py
  tests/test_meilisearch_routes.py
  tests/test_search_routes.py
  tests/test_settings_routes.py
Labels: skip-changelog

#228 Fix typo
  README.md
Labels: skip-changelog

#230 Correct supported Meilisearch version
  README.md
Labels: skip-changelog

#234 Bump mypy pre-commit hook
  .pre-commit-config.yaml
Labels: skip-changelog

#235 Add cov-report to default pytest flags
  pyproject.toml
Labels: skip-changelog
