Repository sanders41/meilisearch-fastapi, pull requests merged in 2023-07, with the labels that each got.

#500 Add matching_strategy: str = "all" to the SearchParameters model on f…
  meilisearch_fastapi/models/search_parameters.py
  meilisearch_fastapi/routes/search_routes.py
  tests/test_search_routes.py
Labels: enhancement

#509 Meilisearch python async 1.4.7
  poetry.lock
  pyproject.toml
  tests/test_meilisearch_routes.py
Labels: dependencies, skip-changelog

#516 Fix typo
  README.md
Labels: skip-changelog
